# Generated by Django 5.1.1 on 2024-10-24 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Welcome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=90)),
                ('text', models.TextField()),
                ('tugma', models.CharField(max_length=90)),
                ('rasm', models.ImageField(upload_to='media/')),
                ('rasm1', models.ImageField(upload_to='media/')),
                ('rasm2', models.ImageField(upload_to='media/')),
                ('rasm3', models.ImageField(upload_to='media/')),
                ('rasm4', models.ImageField(upload_to='media/')),
            ],
        ),
    ]
