# Generated by Django 5.1.1 on 2024-10-24 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='welcome',
            name='rasm',
        ),
        migrations.RemoveField(
            model_name='welcome',
            name='rasm1',
        ),
        migrations.RemoveField(
            model_name='welcome',
            name='rasm2',
        ),
        migrations.RemoveField(
            model_name='welcome',
            name='rasm3',
        ),
        migrations.RemoveField(
            model_name='welcome',
            name='rasm4',
        ),
    ]
