# Generated by Django 5.1.1 on 2024-10-24 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_welcome_rasm_remove_welcome_rasm1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Minus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=90)),
                ('text', models.TextField()),
                ('text1', models.TextField()),
                ('name', models.CharField(max_length=90)),
                ('text2', models.TextField()),
            ],
        ),
    ]
