# Generated by Django 5.1.1 on 2024-10-26 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_sms'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=90)),
                ('text', models.TextField()),
                ('rasm', models.ImageField(upload_to='media/')),
                ('nomi1', models.CharField(max_length=90)),
                ('text1', models.TextField()),
            ],
        ),
    ]
