# Generated by Django 5.1.1 on 2024-10-26 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_cons'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(max_length=90)),
                ('nomi', models.CharField(max_length=90)),
                ('text', models.TextField()),
                ('tugma', models.CharField(max_length=90)),
            ],
        ),
    ]
