# Generated by Django 5.1.1 on 2024-10-29 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_service_icon'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rasm', models.ImageField(upload_to='media/')),
                ('nomi', models.CharField(max_length=90)),
                ('text', models.TextField()),
                ('icon', models.CharField(max_length=90)),
                ('nomi1', models.CharField(max_length=90)),
                ('text1', models.TextField()),
            ],
        ),
    ]
