# Generated by Django 5.1.1 on 2024-10-29 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_mod'),
    ]

    operations = [
        migrations.CreateModel(
            name='Biz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=90)),
                ('text', models.TextField()),
                ('text1', models.TextField()),
                ('text2', models.TextField()),
                ('text3', models.TextField()),
                ('rasm', models.ImageField(upload_to='media/')),
            ],
        ),
        migrations.CreateModel(
            name='Ho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=90)),
                ('text', models.TextField()),
                ('text1', models.TextField()),
                ('text2', models.TextField()),
                ('text3', models.TextField()),
                ('text4', models.TextField()),
                ('rasm', models.ImageField(upload_to='media/')),
            ],
        ),
        migrations.CreateModel(
            name='Tu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=90)),
                ('text', models.TextField()),
                ('text1', models.TextField()),
                ('text2', models.TextField()),
                ('text3', models.TextField()),
                ('rasm', models.ImageField(upload_to='media/')),
            ],
        ),
        migrations.RemoveField(
            model_name='mod',
            name='nomi',
        ),
    ]
