# Generated by Django 5.1.1 on 2024-11-05 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_biz_ho_tu_remove_mod_nomi'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rasm', models.ImageField(upload_to='media/')),
                ('ism', models.CharField(max_length=90)),
                ('ish', models.CharField(max_length=90)),
                ('text', models.TextField()),
            ],
        ),
    ]
