# Generated by Django 5.1.1 on 2024-11-08 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_test'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rasm', models.ImageField(upload_to='media/')),
                ('sana', models.DateField()),
                ('nomi', models.CharField(max_length=90)),
                ('ism', models.CharField(max_length=90)),
                ('ish', models.CharField(max_length=90)),
                ('tugma', models.CharField(max_length=90)),
            ],
        ),
    ]
