# Generated by Django 5.1.1 on 2024-11-14 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_blog1'),
    ]

    operations = [
        migrations.CreateModel(
            name='Et',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rasm', models.ImageField(upload_to='media/')),
                ('nomi', models.CharField(max_length=90)),
                ('sana', models.CharField(max_length=90)),
                ('nomi1', models.CharField(max_length=90)),
                ('text', models.TextField()),
                ('text1', models.TextField()),
                ('text2', models.TextField()),
                ('text3', models.TextField()),
                ('text4', models.TextField()),
            ],
        ),
    ]
