# Generated by Django 5.1.1 on 2024-11-16 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_et'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=90)),
                ('text', models.TextField()),
                ('raqam', models.IntegerField()),
                ('name', models.CharField(max_length=90)),
                ('raqam1', models.IntegerField()),
                ('name1', models.CharField(max_length=90)),
                ('raqam2', models.IntegerField()),
                ('name2', models.CharField(max_length=90)),
                ('raqam3', models.IntegerField()),
                ('name3', models.CharField(max_length=90)),
            ],
        ),
    ]
