# Generated by Django 5.1.1 on 2024-11-19 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_omnis'),
    ]

    operations = [
        migrations.CreateModel(
            name='Est1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=90)),
                ('text', models.TextField()),
                ('icon', models.CharField(max_length=90)),
                ('nomi1', models.CharField(max_length=90)),
                ('text1', models.TextField()),
                ('rasm', models.ImageField(upload_to='media/')),
            ],
        ),
    ]
