# Generated by Django 5.1.1 on 2024-11-21 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_est1'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Est1',
        ),
    ]
