# Generated by Django 5.1.1 on 2024-11-23 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_rasm'),
    ]

    operations = [
        migrations.CreateModel(
            name='This',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=90)),
                ('text', models.TextField()),
                ('text1', models.TextField()),
                ('text2', models.TextField()),
                ('rasm', models.ImageField(upload_to='media/')),
                ('ism', models.CharField(max_length=90)),
                ('ish', models.CharField(max_length=90)),
                ('text3', models.TextField()),
                ('text4', models.TextField()),
            ],
        ),
    ]
