# Generated by Django 5.1.1 on 2024-11-23 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_this'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=90)),
                ('nomi1', models.CharField(max_length=90)),
                ('ish', models.CharField(max_length=90)),
                ('nomi2', models.CharField(max_length=90)),
                ('ish1', models.CharField(max_length=90)),
                ('nomi3', models.CharField(max_length=90)),
                ('ish2', models.CharField(max_length=90)),
                ('nomi4', models.CharField(max_length=90)),
                ('ish3', models.CharField(max_length=90)),
                ('tugma', models.CharField(max_length=90)),
            ],
        ),
    ]
