# Generated by Django 5.1.1 on 2024-11-23 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='Col',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=90)),
                ('ish', models.TextField()),
            ],
        ),
    ]
